### ISSUE TITLE
[Question] How to change the terminal theme?

### ISSUE THREAD

**Issue by waltergallegog** [antmicro/TermSharp#5]
I'm using the Renode framework, and I would like to change the terminal theme to a light one. 
Is it possible to do so from a configuration file?
In the Renode config file I don't see this option:
https://renode.readthedocs.io/en/latest/introduction/using.html#configuring-the-user-interface

Thanks.

**Comment by PiotrZierhoffer** [comment]
Hi @waltergallegog .

Unfortunately there is no support for themes in TermSharp at the moment.

You can play around colors defined in https://github.com/antmicro/TermSharp/blob/master/Terminal.cs#L34, but that would be pretty manual.

I believe that if we consider supporting themes, it will be on the Renode level rather than TermSharp itself. This is not planned at the moment, though, so I can't give you any specific estimates on this.

**Comment by waltergallegog** [comment]
Hi @PiotrZierhoffer 
Thanks a lot for the quick feedback.
For now I will use GnomeTerminal as a workaround, which defaults to a light theme (in my system). 
If in the future I see there is some functionality of TermSharp that I need, I will try with your suggestion.
